# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


ActiveRecord::Base.connection.reset_pk_sequence!(:users)
ActiveRecord::Base.connection.reset_pk_sequence!(:groups)

ApplicationRecord.transaction do 
  puts "Destroying tables..."
  # Unnecessary if using `rails db:seed:replant`
  User.destroy_all

  puts "Resetting primary keys..."
  # For easy testing, so that after seeding, the first `User` has `id` of 1
  ApplicationRecord.connection.reset_pk_sequence!('users')

  puts "Creating users..."
  # Create one user with an easy to remember username, email, and password:
  User.create!(
    username: 'Demo-lition', 
    fname: "Demo",
    lname: "User",
    email: 'demo@user.io', 
    password: 'password'
  )

  # More users
  10.times do 
    User.create!({
      username: Faker::Internet.unique.username(specifier: 3),
      email: Faker::Internet.unique.email,
      fname: Faker::Internet.unique.username,
      lname: Faker::Internet.unique.username,
      password: 'password'
    }) 
  end

  puts "Creating groups"
 Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Tuesday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Tuesday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "TRX Max" ,day_of_week: "Tuesday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Slow Flow Yoga" ,day_of_week: "Tuesday" ,time: "04:00 pm - 05:00 pm" ,instructor_name: "Gustavo Rearte" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "True Barre" ,day_of_week: "Tuesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Cycle Beats" ,day_of_week: "Tuesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "METCON 3" ,day_of_week: "Tuesday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Tabatha Max" ,day_of_week: "Wednesday" ,time: "07:00 am - 07:45 am" ,instructor_name: "Sally French" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Stronger" ,day_of_week: "Wednesday" ,time: "09:30 am - 10:15 am" ,instructor_name: "Tim McGarrigal" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Yoga Sculpt" ,day_of_week: "Wednesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Boxing" ,day_of_week: "Wednesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Precision Run" ,day_of_week: "Wednesday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Thursday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Circuit Training" ,day_of_week: "Thursday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Thursday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Cycle Beats" ,day_of_week: "Thursday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Kelsey Pfeffer" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Cardio Dance" ,day_of_week: "Thursday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Kenny Walter" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "TRX Max" ,day_of_week: "Friday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "True Barre" ,day_of_week: "Friday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Lower Body Blast" ,day_of_week: "Friday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Boxing" ,day_of_week: "Friday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Friday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Athletic Conditioning" ,day_of_week: "Saturday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Boxing" ,day_of_week: "Saturday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Saturday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Precision Run" ,day_of_week: "Saturday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Athletic Stretch" ,day_of_week: "Saturday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Barre" ,day_of_week: "Sunday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Sunday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Boxing" ,day_of_week: "Sunday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Sunday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Sunday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Monday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "TRX Max" ,day_of_week: "Monday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Monday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Precision Run" ,day_of_week: "Monday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Monday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Sports Club San Francisco")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Tuesday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Pine Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Tuesday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Pine Street")
Group.create!(name: "TRX Max" ,day_of_week: "Tuesday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Pine Street")
Group.create!(name: "Slow Flow Yoga" ,day_of_week: "Tuesday" ,time: "04:00 pm - 05:00 pm" ,instructor_name: "Gustavo Rearte" ,location: "Equinox Pine Street")
Group.create!(name: "True Barre" ,day_of_week: "Tuesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Tuesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "METCON 3" ,day_of_week: "Tuesday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Pine Street")
Group.create!(name: "Tabatha Max" ,day_of_week: "Wednesday" ,time: "07:00 am - 07:45 am" ,instructor_name: "Sally French" ,location: "Equinox Pine Street")
Group.create!(name: "Stronger" ,day_of_week: "Wednesday" ,time: "09:30 am - 10:15 am" ,instructor_name: "Tim McGarrigal" ,location: "Equinox Pine Street")
Group.create!(name: "Yoga Sculpt" ,day_of_week: "Wednesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Boxing" ,day_of_week: "Wednesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "Precision Run" ,day_of_week: "Wednesday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Pine Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Thursday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Circuit Training" ,day_of_week: "Thursday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Pine Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Thursday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Pine Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Thursday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Kelsey Pfeffer" ,location: "Equinox Pine Street")
Group.create!(name: "Cardio Dance" ,day_of_week: "Thursday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Kenny Walter" ,location: "Equinox Pine Street")
Group.create!(name: "TRX Max" ,day_of_week: "Friday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Pine Street")
Group.create!(name: "True Barre" ,day_of_week: "Friday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Lower Body Blast" ,day_of_week: "Friday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Pine Street")
Group.create!(name: "Boxing" ,day_of_week: "Friday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Pine Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Friday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "Athletic Conditioning" ,day_of_week: "Saturday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Pine Street")
Group.create!(name: "Boxing" ,day_of_week: "Saturday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Pine Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Saturday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Precision Run" ,day_of_week: "Saturday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Pine Street")
Group.create!(name: "Athletic Stretch" ,day_of_week: "Saturday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "Barre" ,day_of_week: "Sunday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Pine Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Sunday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Pine Street")
Group.create!(name: "Boxing" ,day_of_week: "Sunday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Sunday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Pine Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Sunday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Monday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Pine Street")
Group.create!(name: "TRX Max" ,day_of_week: "Monday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Pine Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Monday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Pine Street")
Group.create!(name: "Precision Run" ,day_of_week: "Monday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Pine Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Monday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Pine Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Tuesday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Union Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Tuesday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Union Street")
Group.create!(name: "TRX Max" ,day_of_week: "Tuesday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Union Street")
Group.create!(name: "Slow Flow Yoga" ,day_of_week: "Tuesday" ,time: "04:00 pm - 05:00 pm" ,instructor_name: "Gustavo Rearte" ,location: "Equinox Union Street")
Group.create!(name: "True Barre" ,day_of_week: "Tuesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Tuesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "METCON 3" ,day_of_week: "Tuesday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Union Street")
Group.create!(name: "Tabatha Max" ,day_of_week: "Wednesday" ,time: "07:00 am - 07:45 am" ,instructor_name: "Sally French" ,location: "Equinox Union Street")
Group.create!(name: "Stronger" ,day_of_week: "Wednesday" ,time: "09:30 am - 10:15 am" ,instructor_name: "Tim McGarrigal" ,location: "Equinox Union Street")
Group.create!(name: "Yoga Sculpt" ,day_of_week: "Wednesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Boxing" ,day_of_week: "Wednesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "Precision Run" ,day_of_week: "Wednesday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Union Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Thursday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Circuit Training" ,day_of_week: "Thursday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Union Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Thursday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Union Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Thursday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Kelsey Pfeffer" ,location: "Equinox Union Street")
Group.create!(name: "Cardio Dance" ,day_of_week: "Thursday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Kenny Walter" ,location: "Equinox Union Street")
Group.create!(name: "TRX Max" ,day_of_week: "Friday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Union Street")
Group.create!(name: "True Barre" ,day_of_week: "Friday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Lower Body Blast" ,day_of_week: "Friday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Union Street")
Group.create!(name: "Boxing" ,day_of_week: "Friday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Union Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Friday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "Athletic Conditioning" ,day_of_week: "Saturday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Union Street")
Group.create!(name: "Boxing" ,day_of_week: "Saturday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Union Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Saturday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Precision Run" ,day_of_week: "Saturday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Union Street")
Group.create!(name: "Athletic Stretch" ,day_of_week: "Saturday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "Barre" ,day_of_week: "Sunday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Union Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Sunday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Union Street")
Group.create!(name: "Boxing" ,day_of_week: "Sunday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Sunday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Union Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Sunday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Monday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Union Street")
Group.create!(name: "TRX Max" ,day_of_week: "Monday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Union Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Monday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Union Street")
Group.create!(name: "Precision Run" ,day_of_week: "Monday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Union Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Monday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Union Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Tuesday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Beale Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Tuesday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Beale Street")
Group.create!(name: "TRX Max" ,day_of_week: "Tuesday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Beale Street")
Group.create!(name: "Slow Flow Yoga" ,day_of_week: "Tuesday" ,time: "04:00 pm - 05:00 pm" ,instructor_name: "Gustavo Rearte" ,location: "Equinox Beale Street")
Group.create!(name: "True Barre" ,day_of_week: "Tuesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Tuesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "METCON 3" ,day_of_week: "Tuesday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Beale Street")
Group.create!(name: "Tabatha Max" ,day_of_week: "Wednesday" ,time: "07:00 am - 07:45 am" ,instructor_name: "Sally French" ,location: "Equinox Beale Street")
Group.create!(name: "Stronger" ,day_of_week: "Wednesday" ,time: "09:30 am - 10:15 am" ,instructor_name: "Tim McGarrigal" ,location: "Equinox Beale Street")
Group.create!(name: "Yoga Sculpt" ,day_of_week: "Wednesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Boxing" ,day_of_week: "Wednesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "Precision Run" ,day_of_week: "Wednesday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Beale Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Thursday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Circuit Training" ,day_of_week: "Thursday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Beale Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Thursday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Beale Street")
Group.create!(name: "Cycle Beats" ,day_of_week: "Thursday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Kelsey Pfeffer" ,location: "Equinox Beale Street")
Group.create!(name: "Cardio Dance" ,day_of_week: "Thursday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Kenny Walter" ,location: "Equinox Beale Street")
Group.create!(name: "TRX Max" ,day_of_week: "Friday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Beale Street")
Group.create!(name: "True Barre" ,day_of_week: "Friday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Lower Body Blast" ,day_of_week: "Friday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Beale Street")
Group.create!(name: "Boxing" ,day_of_week: "Friday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Beale Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Friday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "Athletic Conditioning" ,day_of_week: "Saturday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Beale Street")
Group.create!(name: "Boxing" ,day_of_week: "Saturday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Beale Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Saturday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Precision Run" ,day_of_week: "Saturday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Beale Street")
Group.create!(name: "Athletic Stretch" ,day_of_week: "Saturday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "Barre" ,day_of_week: "Sunday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Beale Street")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Sunday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Beale Street")
Group.create!(name: "Boxing" ,day_of_week: "Sunday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Sunday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Beale Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Sunday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Monday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Beale Street")
Group.create!(name: "TRX Max" ,day_of_week: "Monday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Beale Street")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Monday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Beale Street")
Group.create!(name: "Precision Run" ,day_of_week: "Monday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Beale Street")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Monday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Beale Street")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Tuesday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Van Mission")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Tuesday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Van Mission")
Group.create!(name: "TRX Max" ,day_of_week: "Tuesday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Van Mission")
Group.create!(name: "Slow Flow Yoga" ,day_of_week: "Tuesday" ,time: "04:00 pm - 05:00 pm" ,instructor_name: "Gustavo Rearte" ,location: "Equinox Van Mission")
Group.create!(name: "True Barre" ,day_of_week: "Tuesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Cycle Beats" ,day_of_week: "Tuesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")
Group.create!(name: "METCON 3" ,day_of_week: "Tuesday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Van Mission")
Group.create!(name: "Tabatha Max" ,day_of_week: "Wednesday" ,time: "07:00 am - 07:45 am" ,instructor_name: "Sally French" ,location: "Equinox Van Mission")
Group.create!(name: "Stronger" ,day_of_week: "Wednesday" ,time: "09:30 am - 10:15 am" ,instructor_name: "Tim McGarrigal" ,location: "Equinox Van Mission")
Group.create!(name: "Yoga Sculpt" ,day_of_week: "Wednesday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Boxing" ,day_of_week: "Wednesday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")
Group.create!(name: "Precision Run" ,day_of_week: "Wednesday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Van Mission")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Thursday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Circuit Training" ,day_of_week: "Thursday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Van Mission")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Thursday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Van Mission")
Group.create!(name: "Cycle Beats" ,day_of_week: "Thursday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Kelsey Pfeffer" ,location: "Equinox Van Mission")
Group.create!(name: "Cardio Dance" ,day_of_week: "Thursday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Kenny Walter" ,location: "Equinox Van Mission")
Group.create!(name: "TRX Max" ,day_of_week: "Friday" ,time: "12:15 pm - 01:00 pm" ,instructor_name: "Stephanie Vu" ,location: "Equinox Van Mission")
Group.create!(name: "True Barre" ,day_of_week: "Friday" ,time: "05:30 pm - 06:15 pm" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Lower Body Blast" ,day_of_week: "Friday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Rayson Yam" ,location: "Equinox Van Mission")
Group.create!(name: "Boxing" ,day_of_week: "Friday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Van Mission")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Friday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")
Group.create!(name: "Athletic Conditioning" ,day_of_week: "Saturday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Van Mission")
Group.create!(name: "Boxing" ,day_of_week: "Saturday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Van Mission")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Saturday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Precision Run" ,day_of_week: "Saturday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Van Mission")
Group.create!(name: "Athletic Stretch" ,day_of_week: "Saturday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")
Group.create!(name: "Barre" ,day_of_week: "Sunday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Van Mission")
Group.create!(name: "Best Butt Ever" ,day_of_week: "Sunday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Van Mission")
Group.create!(name: "Boxing" ,day_of_week: "Sunday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Sunday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Van Mission")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Sunday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")
Group.create!(name: "Vinyasa Yoga" ,day_of_week: "Monday" ,time: "10:00 am - 10:45 am" ,instructor_name: "Precious Moreno" ,location: "Equinox Van Mission")
Group.create!(name: "TRX Max" ,day_of_week: "Monday" ,time: "04:15 pm - 05:00 pm" ,instructor_name: "Fady Asaad" ,location: "Equinox Van Mission")
Group.create!(name: "Best Abs Ever" ,day_of_week: "Monday" ,time: "07:30 am - 08:30 am" ,instructor_name: "Colette Hernandez" ,location: "Equinox Van Mission")
Group.create!(name: "Precision Run" ,day_of_week: "Monday" ,time: "06:00 pm - 06:45 pm" ,instructor_name: "Mark Protacio" ,location: "Equinox Van Mission")
Group.create!(name: "Pilates Fusion" ,day_of_week: "Monday" ,time: "06:30 pm - 07:20 pm" ,instructor_name: "Helen Saunders" ,location: "Equinox Van Mission")



  puts "Done!"
end